language: go
go:
- 1.4
node_js:
- '0.11'
sudo: required
install:
- nvm install 0.11
- npm install grunt-cli -g
- npm install --save-dev grunt string toml conzole
- wget https://github.com/spf13/hugo/releases/download/v0.15/hugo_0.15_linux_amd64.tar.gz
- tar zxvf hugo_0.15_linux_amd64.tar.gz
- mkdir -p $HOME/bin
- mv hugo_0.15_linux_amd64/hugo_0.15_linux_amd64 $HOME/bin/hugo
- echo $GOPATH
- export PATH=$PATH:$HOME/bin:$GOPATH/bin
- go get github.com/goadesign/goa
- go get github.com/goadesign/middleware
- go get github.com/goadesign/encoding
- go get github.com/goadesign/logging/...
- go get github.com/goadesign/gorma
- cd tools/godoc2md && go get -v ./... && go build -o $HOME/bin/godoc2md && cd ../..
- cd tools/mdc && go get -v ./... && go build -o $HOME/bin/mdc && cd ../..
- sudo pip install Pygments
script:
- make docs
- hugo --theme=goa
- grunt lunr-index
deploy:
  provider: gcs
  access_key_id: GOOGDIIIVPY7O6DG3PSZ
  secret_access_key:
    secure: CQwXvp4mZ/IAr2Pp7dlhp73rfrHc4I5rGuCdc6TIWbAmL0JOAGooQfRXpvESpTFf2xpvlamHVnH5aP6SjEVo7bVyeQvheMDQJ1YVqNULQXpEFkbA7vqmQgBB6D5I2Za9PLKD17Ep5ZYS1zDDWRhix/1MI4337Y+JSYq7lrVjLT9kbSciHyaUCr7Anf5R2FDpzhgq4wOy4SNKewjmbdOQhPFZbPPy1ufMrWWOdS/Ot1ww8xkrT/7ClDSYQ3odXX8L/KB33qFIvnscaKWx5zmNkW+Yy0Qh4kNhgYXCEWqCOsLw0aWFp8syLLHsgs8+Yv8pa48rqlbo+T5Ql/PbyXw2CM8UjPQvphMh2Ly9Y/Q0I/zAoHDsZ/uu22FBaEDLkVw29TigvCLLHk95YjgZJSd0gpEWsNYe4tgFuxG7m5S9+JOykrqr449/qDdRbNoyGYkawlMzVnl4m3dpO/so79KxJLwXteiPO453YAJ1x9s438zEbFjMhRstAL1SmX45Gn2atfg91KjK6lkvlHhUOd/Fz5AsXnm52Vzf3RSJ04z4bPlDY0XfQeYYqP9muzdTgxqCQXUKeiUer06b8+VrjaOwe/g2ITjEvEHb482iwaYNgqHOoF00yUpDpRQB11+ArD8rao/Fk5GNuWB7TQCdLNJLr+IAZwJQ7raM92oCxMdzTEA=
  bucket: goa.design
  local-dir: public
  skip-cleanup: true
  acl: public-read
  cache-control: max-age=300
  on:
    repo: goadesign/goa.design
