baseurl = "http://goa.design/"
languageCode = "en-us"
title = "goa - Design First. Then Win."
theme = "goa"
uglyURLs = true
pluralizelisttitles = false

pygmentscodefences = true
pygmentsoptions = ""
pygmentsstyle = "friendly"
pygmentsuseclasses = false

[taxonomies]
tag = "tags"
category = "categories"
series = "series"
