name = "goa"
baseurl = "https://goa.design/"
description = "goa - Design First. Then Win."
homepage = "https://goa.design"
license = "MIT"
licenselink = "https://github.com/goadesign/goa.design/blob/master/LICENSE"

uglyURLs = false
pluralizelisttitles = false
pygmentscodefences = true
pygmentsoptions = ""
pygmentsstyle = "friendly"
pygmentsuseclasses = false

[author]
name = "goa contributors"
homepage = "https://github.com/goadesign"

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

DefaultContentLanguage = "en" 

[languages.en] 
weight = 1 
title = "goa - Design First. Then Win." 
languageName = "English"
 
[languages.ja] 
weight = 2 
title = "goa - はじめにデザインを。そして成功を。" 
languageName = "日本語"

[[languages.en.menu.main]]
name = "v2"
identifier = "v2"
url = "/v2/"
weight = 1

[[languages.en.menu.main]]
name = "v1"
identifier = "v1"
url = "/v1/"
weight = 2

[[languages.en.menu.main]]
name = "Learn"
identifier = "learn"
url = "/v1/learn/"
parent = "v1"
weight = 1

[[languages.en.menu.main]]
name = "Design"
identifier = "design"
url = "/v1/design/"
parent = "v1"
weight = 2

[[languages.en.menu.main]]
name = "Implement"
identifier = "implement"
url = "/v1/implement/"
parent = "v1"
weight = 3

[[languages.en.menu.main]]
name = "Extend"
identifier = "extend"
url = "/v1/extend/"
parent = "v1"
weight = 4

[[languages.en.menu.main]]
name = "Blog"
identifier = "blog"
url = "/blog/"
weight = 3

[[languages.ja.menu.main]]
name = "学ぶ"
identifier = "learn"
url = "/ja/v1/learn/"
weight = 2

[[languages.ja.menu.main]]
name = "デザイン"
identifier = "design"
url = "/ja/v1/design/"
weight = 3

[[languages.ja.menu.main]]
name = "実装する"
identifier = "implement"
url = "/ja/v1/implement/"
weight = 4

[[languages.ja.menu.main]]
name = "拡張する"
identifier = "extend"
url = "/ja/v1/extend/"
weight = 5

[[languages.ja.menu.main]]
name = "ブログ"
identifier = "blog"
url = "/ja/blog/"
weight = 6
