# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "goa"
license = "MIT"
licenselink = "https://github.com/goadesign/goa.design/blob/master/LICENSE"
description = "goa - Design First. Then Win."
homepage = "http://goa.design"
tags = ["", ""]
features = ["", ""]
min_version = 0.15

[author]
  name = "goa contributors"
  homepage = "https://github.com/goadesign/goa"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
