name = "goa"
description = "goa - Design First. Then Win."
homepage = "http://goa.design"
license = "MIT"
licenselink = "https://github.com/goadesign/goa.design/blob/master/LICENSE"

[author]
  name = "goa contributors"
  homepage = "https://github.com/goadesign/goa"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
